- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: true
  become: true

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Create Prometheus config directory
  file:
    path: /opt/prometheus
    state: directory
    mode: '0755'
  become: true

- name: Copy Prometheus config
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Remove old Prometheus container if exists
  docker_container:
    name: prometheus
    state: absent
  become: true

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  become: true
