---
- name: Ensure kubectl is installed on control-plane
  apt:
    name: kubectl
    state: present
  when: inventory_hostname in groups['control-plane_group']

- name: Label frontend node
  kubernetes.core.k8s:
    state: present
    kind: Node
    name: frontend
    definition:
      metadata:
        labels:
          node-role: frontend
  when: inventory_hostname in groups['control-plane_group']

- name: Check if regcred secret exists
  kubernetes.core.k8s_info:
    kind: Secret
    name: regcred
    namespace: default
  register: regcred_secret
  when: inventory_hostname in groups['control-plane_group']

- name: Create Docker Hub credentials secret if not exists
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../backend/templates/regcred-secret.yaml.j2') }}"
  vars:
    dockerconfigjson: |
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "{{ dockerhub_username }}",
            "password": "{{ dockerhub_password }}",
            "auth": "{{ (dockerhub_username + ':' + dockerhub_password) | b64encode }}"
          }
        }
      }
  when:
    - inventory_hostname in groups['control-plane_group']
    - regcred_secret.resources | length == 0

- name: Apply Frontend Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'frontend-service.yaml.j2') }}"
  when: inventory_hostname in groups['control-plane_group']

- name: Apply Frontend Deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'frontend-deployment.yaml.j2') }}"
  when: inventory_hostname in groups['control-plane_group']
