---
- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | HELM_INSTALL_DIR=/usr/local/bin bash
  args:
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version }}"

- name: Create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"