---
- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Install Helm
  ansible.builtin.shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Check Helm version
  ansible.builtin.command: helm version
  register: helm_version
  changed_when: false

- name: Show Helm version
  ansible.builtin.debug:
    msg: "Helm installed successfully: {{ helm_version.stdout }}"
