- name: Check if node_exporter is already installed
  stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_bin

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
  when: not node_exporter_bin.stat.exists

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes
  when: not node_exporter_bin.stat.exists

- name: Move node_exporter binary
  copy:
    remote_src: yes
    src: /tmp/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
  when: not node_exporter_bin.stat.exists

- name: Create systemd service for node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: Restart node_exporter

- name: Ensure node_exporter is enabled and started
  systemd:
    name: node_exporter
    enabled: yes
    state: started
