repos:
  - name: "Backend"
    repo: "{{ GITHUB_REPO_BACKEND }}"
    dest: "~/k3s/backend"
  - name: "Frontend"
    repo: "{{ GITHUB_REPO_FRONTEND }}"
    dest: "~/k3s/frontend"
  - name: "Redis"
    repo: "{{ GITHUB_REPO_REDIS }}"
    dest: "~/k3s/redis"
  - name: "Postgres"
    repo: "{{ GITHUB_REPO_DATABASE }}"
    dest: "~/k3s/database"
