---
- name: Create registry secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ registry_secret_name }}"
        namespace: "{{ namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ lookup('env', 'DOCKER_AUTH') | b64encode }}"
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

- name: Create TLS secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ tls_secret_name }}"
        namespace: "{{ namespace }}"
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('env', 'TLS_CERT') | b64encode }}"
        tls.key: "{{ lookup('env', 'TLS_KEY') | b64encode }}"
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"