---
- name: Ensure kubectl is installed on control-plane
  apt:
    name: kubectl
    state: present
  when: inventory_hostname in groups['control-plane_group']

- name: Install Nginx Ingress Controller
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    state: present
    chart_version: "4.11.2"
    values:
      controller:
        service:
          type: ClusterIP
  when: inventory_hostname in groups['control-plane_group']

- name: Apply Ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yaml.j2') }}"
  when: inventory_hostname in groups['control-plane_group']
