global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets:
          - '10.0.2.3:9100'
          - '10.0.2.4:9100'
          - '10.0.2.5:9100'
          - '10.0.2.6:9100'
