- name: Add Datadog Helm repository
  ansible.builtin.command:
    cmd: helm repo add datadog https://helm.datadoghq.com
  changed_when: true

- name: Update Helm repositories
  ansible.builtin.command:
    cmd: helm repo update
  changed_when: true

- name: Create monitoring namespace
  ansible.builtin.command:
    cmd: kubectl create namespace {{ datadog_namespace }}
  register: namespace_result
  failed_when: namespace_result.rc != 0 and 'AlreadyExists' not in namespace_result.stderr
  changed_when: namespace_result.rc == 0

- name: Create Datadog Helm values file
  ansible.builtin.template:
    src: datadog-values.yaml.j2
    dest: "{{ playbook_dir }}/datadog-values.yaml"
    mode: '0644'

- name: Deploy Datadog Helm chart
  ansible.builtin.command:
    cmd: >
      helm upgrade --install {{ release_name }}
      datadog/datadog
      --version {{ chart_version }}
      --namespace {{ datadog_namespace }}
      --values {{ playbook_dir }}/datadog-values.yaml
      --wait
  changed_when: true

- name: Verify Datadog deployment
  ansible.builtin.command:
    cmd: kubectl get pods -n {{ datadog_namespace }} -l app.kubernetes.io/instance=datadog -o jsonpath='{.items[*].metadata.name}'
  register: datadog_pods
  until: datadog_pods.stdout | length > 0
  retries: 10
  delay: 30