- name: Install K3s master
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s service to be active
  systemd:
    name: k3s
    state: started
    enabled: yes

- name: Read k3s token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_base64

- name: Set k3s_token fact
  set_fact:
    k3s_token: "{{ k3s_token_base64.content | b64decode }}"

- name: Debug token (optional, remove in prod)
  debug:
    msg: "K3s token: {{ k3s_token }}"
