- name: Wait for k3s master IP and token from master
  wait_for:
    host: "{{ k3s_master_ip }}"
    port: 6443
    timeout: 300

- name: Install K3s agent (worker)
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s agent service is started and enabled
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
