---
- name: Create /var/lib/rancher/k3s directory
  file:
    path: /var/lib/rancher/k3s
    state: directory
    mode: '0755'

- name: Create k3s service environment file
  template:
    src: k3s_env.j2
    dest: /etc/systemd/system/k3s.service.env
    mode: '0644'

- name: Create k3s service file
  copy:
    content: |
      [Unit]
      Description=Lightweight Kubernetes
      Documentation=https://k3s.io
      After=network.target

      [Service]
      Type=notify
      EnvironmentFile=/etc/systemd/system/k3s.service.env
      ExecStart={{ k3s_install_dir }}/k3s server {{ k3s_server_options }}
      KillMode=process
      Delegate=yes
      LimitNOFILE=1048576
      LimitNPROC=1048576
      LimitCORE=1048576
      TasksMax=infinity
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/k3s.service
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and start k3s service
  systemd:
    name: k3s
    enabled: yes
    state: started

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'
  become: true

- name: Copy kubeconfig to user home
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
  become: true

- name: Set correct permissions for kubeconfig
  file:
    path: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: 'export KUBECONFIG=/home/{{ ansible_user }}/.kube/config'
    create: yes
  become: true