---
- name: Install prerequisites
  apt:
    name:
      - curl
      - iptables
    state: present
    update_cache: yes

- name: Download k3s binary
  get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "{{ k3s_install_dir }}/k3s"
    mode: '0755'

- name: Ensure k3s binary is executable
  file:
    path: "{{ k3s_install_dir }}/k3s"
    mode: '0755'