---
- name: Install k3s
  include_tasks: install_k3s.yml

- name: Configure k3s for control-plane
  include_tasks: configure_control_plane.yml
  when: k3s_role == "server"

- name: Configure k3s for workers
  include_tasks: configure_worker.yml
  when: k3s_role == "agent"