---
- name: Install and configure k3s control plane
  hosts: control_plane_group
  become: true
  vars:
    k3s_role: "server"
    k3s_server_options: "--cluster-init --disable=traefik --disable=servicelb"
  roles:
    - k3s

- name: Fetch k3s token from control plane
  hosts: control_plane_group
  become: true
  tasks:
    - name: Wait for token
      wait_for:
        path: /var/lib/rancher/k3s/server/token
        state: present
      delegate_to: "{{ groups['control_plane_group'][0] }}"
      delay: 5
      timeout: 60

    - name: Retrieve k3s token
      slurp:
        src: /var/lib/rancher/k3s/server/token
      register: k3s_token_file

    - name: Set k3s_token fact
      set_fact:
        k3s_token: "{{ k3s_token_file.content | b64decode | trim }}"

- name: Install and configure k3s workers
  hosts: workers_group
  become: true
  vars:
    k3s_role: "agent"
    k3s_token: "{{ hostvars[groups['control_plane_group'][0]]['k3s_token'] }}"
  roles:
    - k3s