---
- name: Update Helm values files for all components
  hosts: control_plane
  become: true

  vars_files:
    - "{{ values_file | default('') }}"

  vars:
    db_dump_path: "{{ db_dump_path | default('') }}"

  roles:
    - update_values
