---
- name: Ensure kubectl is installed on control-plane
  apt:
    name: kubectl
    state: present
  when: inventory_hostname in groups['control_plane_group']

- name: Create Docker Hub credentials secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'regcred-secret.yaml.j2') }}"
  vars:
    dockerconfigjson: |
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "{{ dockerhub_username }}",
            "password": "{{ dockerhub_password }}",
            "email": "{{ dockerhub_email }}",
            "auth": "{{ (dockerhub_username + ':' + dockerhub_password + ':' + dockerhub_email) | b64encode }}"
          }
        }
      }
  when: inventory_hostname in groups['control_plane_group']

- name: Apply Backend Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'backend-service.yaml.j2') }}"
  when: inventory_hostname in groups['control_plane_group']

- name: Apply Backend Deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'backend-deployment.yaml.j2') }}"
  when: inventory_hostname in groups['control_plane_group']
