- name: Install Git if not present
  become: true
  apt:
    name: git
    state: present
    update_cache: yes

- name: Ensure k3s directory exists
  file:
    path: "~/k3s"
    state: directory
    mode: '0755'

- name: Copy SSH key to control plane
  copy:
    src: "{{ ssh_key_path }}"
    dest: "~/.ssh/id_rsa"
    mode: '0600'

- name: Disable StrictHostKeyChecking
  lineinfile:
    path: "~/.ssh/config"
    line: "StrictHostKeyChecking no"
    create: yes
    mode: '0600'

- name: Clone or update repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: main
    accept_hostkey: yes
    update: yes
    key_file: "~/.ssh/id_rsa"
  with_items:
    - { name: "Backend",  repo: "{{ github_repo_backend }}",  dest: "~/k3s/backend" }
    - { name: "Frontend", repo: "{{ github_repo_frontend }}", dest: "~/k3s/frontend" }
    - { name: "Redis",    repo: "{{ github_repo_redis }}",    dest: "~/k3s/redis" }
    - { name: "Postgres", repo: "{{ github_repo_database }}", dest: "~/k3s/database" }