- name: Create namespace if not exists
  command: >
    kubectl create namespace {{ namespace }}

- name: Create Docker registry secret
  command: >
    kubectl create secret docker-registry regcred
      --docker-username={{ docker_user }}
      --docker-password={{ docker_pass }}
      --docker-email={{ docker_email }}
      --namespace={{ namespace }}

- name: Create TLS secret
  command: >
    kubectl create secret tls tls-secret
    --cert={{ tls_crt }}
    --key={{ tls_key }}
    --namespace={{ namespace }}