---
- name: Create namespace manifest
  copy:
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    dest: /tmp/namespace.yaml

- name: Apply namespace manifest
  shell: kubectl apply -f /tmp/namespace.yaml

- name: Prepare Docker config JSON content
  set_fact:
    docker_config_json: |
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "{{ docker_user }}",
            "password": "{{ docker_pass }}",
            "email": "{{ docker_email }}",
            "auth": "{{ (docker_user + ':' + docker_pass) | b64encode }}"
          }
        }
      }


- name: Encode Docker config JSON to base64
  set_fact:
    docker_config_json_b64: "{{ docker_config_json | to_nice_json | b64encode }}"

- name: Encode TLS cert and key to base64
  set_fact:
    tls_crt_b64: "{{ tls_crt | b64encode }}"
    tls_key_b64: "{{ tls_key | b64encode }}"

- name: Create Docker registry secret YAML from template
  template:
    src: docker-secret.yaml.j2
    dest: /tmp/docker-secret.yaml

- name: Create TLS secret YAML from template
  template:
    src: tls-secret.yaml.j2
    dest: /tmp/tls-secret.yaml

- name: Apply Docker registry secret
  shell: kubectl apply -f /tmp/docker-secret.yaml

- name: Apply TLS secret
  shell: kubectl apply -f /tmp/tls-secret.yaml
