datadog_namespace: "datadog"
datadog_release: "datadog"
datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
datadog_site: "datadoghq.us5"
datadog_domain: "monitoring.class-schedule-app.pp.ua"
tls_cert_path: "/etc/ssl/certs/tls.crt"
tls_key_path: "/etc/ssl/private/tls.key"
